name: Create Release

on:
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}

jobs:
  run:
    name: Create Release
    runs-on: self-hosted
    environment: prod
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Setup Task
        uses: illbjorn/setup-task@main

      - name: Build Skal Binaries
        shell: bash
        run: task bci

      - name: Create the GitHub Release
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          task cr \
            tag="$(task v)" \
            title="Skal Release: $(task v)" \
            body="$(task rn)"
