name: On Merge to Main

on:
  push:
    branches: [main]
    paths: ['**/*.go', 'go.mod', 'go.sum']

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}

jobs:
  create-release:
    name: Create Release
    uses: ./.github/workflows/create-release.yml
    permissions:
      # Required to create the release.
      contents: write
